# BloodHorn EDK2 Bootloader - Woodpecker CI Configuration

# Variables
variables:
  EDK2_VERSION: "edk2-stable202308"
  UBUNTU_IMAGE: "ubuntu:22.04"

# Workspace shared across steps
workspace:
  base: /drone/src
  path: .

steps:
  # Install build dependencies
  install-deps:
    image: ${UBUNTU_IMAGE}
    commands:
      - apt-get update
      - apt-get install -y build-essential nasm gcc-multilib python3 uuid-dev git wget
      - apt-get install -y gcc-mingw-w64-i686

  # Setup EDK2
  setup-edk2:
    image: ${UBUNTU_IMAGE}
    depends_on: [install-deps]
    commands:
      - git clone https://github.com/tianocore/edk2.git --branch ${EDK2_VERSION} --depth 1 edk2
      - cd edk2
      - git submodule update --init
      - make -C BaseTools
      - export EDK_TOOLS_PATH=$(pwd)/BaseTools
      - export PATH=$EDK_TOOLS_PATH/BinWrappers:$PATH
      - cp -r ../BloodHorn ./BloodHorn/
      - echo "EDK2 setup complete"

  # Build for X64
  build-x64:
    image: ${UBUNTU_IMAGE}
    depends_on: [setup-edk2]
    commands:
      - cd edk2/BloodHorn
      - export EDK_TOOLS_PATH=../BaseTools
      - export PATH=$EDK_TOOLS_PATH/BinWrappers:$PATH
      - build -p BloodHorn.dsc -a X64 -b RELEASE -t GCC5
      - echo "Build X64 completed"
      - ls -la Build/BloodHorn/RELEASE_GCC5/X64/

  # Build for ARM64 (optional)
  build-arm64:
    image: ${UBUNTU_IMAGE}
    depends_on: [setup-edk2]
    commands:
      - cd edk2/BloodHorn
      - export EDK_TOOLS_PATH=../BaseTools
      - export PATH=$EDK_TOOLS_PATH/BinWrappers:$PATH
      - build -p BloodHorn.dsc -a AARCH64 -b RELEASE -t GCC5 || echo "ARM64 build failed or not supported"
      - ls -la Build/BloodHorn/RELEASE_GCC5/AARCH64/ || echo "No ARM64 artifacts found"
    allow_failure: true

  # Validate artifacts
  validate:
    image: ${UBUNTU_IMAGE}
    depends_on: [build-x64, build-arm64]
    commands:
      - cd edk2/BloodHorn
      - test -f Build/BloodHorn/RELEASE_GCC5/X64/BloodHorn.efi || exit 1
      - echo "Build validation passed!"
      - echo "Artifacts:"
      - find Build/ -name "*.efi" -o -name "*.fd" | head -10

# Trigger pipeline on main branch
trigger:
  event:
    - push
    - pull_request
  branch:
    - main
