# BloodHorn EDK2 Bootloader - Woodpecker CI

# Events to trigger the pipeline
when:
  event:
    - push
    - pull_request
  branch:
    - main

# Variables
variables:
  EDK2_VERSION: "edk2-stable202308"

steps:
  - name: install-deps
    image: ubuntu:22.04
    commands:
      - apt-get update
      - apt-get install -y build-essential nasm gcc-multilib python3 uuid-dev git wget
      - apt-get install -y gcc-mingw-w64-i686

  - name: setup-edk2
    image: ubuntu:22.04
    depends_on: [install-deps]
    commands:
      - git clone https://github.com/tianocore/edk2.git --branch ${EDK2_VERSION} --depth 1 edk2
      - cd edk2
      - git submodule update --init
      - make -C BaseTools
      - export EDK_TOOLS_PATH=$(pwd)/BaseTools
      - export PATH=$EDK_TOOLS_PATH/BinWrappers:$PATH
      - cp -r ../BloodHorn ./BloodHorn/
      - echo "EDK2 setup complete"

  - name: build-x64
    image: ubuntu:22.04
    depends_on: [setup-edk2]
    commands:
      - cd edk2/BloodHorn
      - export EDK_TOOLS_PATH=../BaseTools
      - export PATH=$EDK_TOOLS_PATH/BinWrappers:$PATH
      - build -p BloodHorn.dsc -a X64 -b RELEASE -t GCC5
      - echo "Build X64 completed"
      - ls -la Build/BloodHorn/RELEASE_GCC5/X64/

  - name: build-arm64
    image: ubuntu:22.04
    depends_on: [setup-edk2]
    commands:
      - cd edk2/BloodHorn
      - export EDK_TOOLS_PATH=../BaseTools
      - export PATH=$EDK_TOOLS_PATH/BinWrappers:$PATH
      - build -p BloodHorn.dsc -a AARCH64 -b RELEASE -t GCC5 || echo "ARM64 build skipped"
      - ls -la Build/BloodHorn/RELEASE_GCC5/AARCH64/ || echo "No ARM64 artifacts"

  - name: validate
    image: ubuntu:22.04
    depends_on: [build-x64, build-arm64]
    commands:
      - cd edk2/BloodHorn
      - test -f Build/BloodHorn/RELEASE_GCC5/X64/BloodHorn.efi || exit 1
      - echo "Build validation passed!"
      - echo "Available artifacts:"
      - find Build/ -name "*.efi" -o -name "*.fd" | head -10
