# .woodpecker.yml
steps:

  build_i386:
    image: archlinux:latest
    commands:
      - pacman -Sy --noconfirm gcc make nasm
      - |
        echo "=== Building for i386 ==="
        set +e
        make ARCH=i386
        STATUS=$?
        echo "i386 exit code: $STATUS"
        exit 0

  build_x86_64:
    image: archlinux:latest
    commands:
      - pacman -Sy --noconfirm gcc make nasm
      - |
        echo "=== Building for x86_64 ==="
        set +e
        make ARCH=x86_64
        STATUS=$?
        echo "x86_64 exit code: $STATUS"
        exit 0

  build_arm32:
    image: multiarch/alpine:armhf-latest
    commands:
      - apk add build-base make bash
      - |
        echo "=== Building for ARM32 ==="
        set +e
        make ARCH=arm
        STATUS=$?
        echo "arm32 exit code: $STATUS"
        exit 0

  build_aarch64:
    image: multiarch/alpine:aarch64-latest
    commands:
      - apk add build-base make bash
      - |
        echo "=== Building for AArch64 ==="
        set +e
        make ARCH=aarch64
        STATUS=$?
        echo "aarch64 exit code: $STATUS"
        exit 0

  build_riscv64:
    image: debian:stable
    commands:
      - apt update && apt install -y build-essential make gcc-riscv64-linux-gnu
      - |
        echo "=== Building for RISC-V64 ==="
        set +e
        make ARCH=riscv64
        STATUS=$?
        echo "riscv64 exit code: $STATUS"
        exit 0
